version: "2"
services:
  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    expose:
      - 3306
    restart: on-failure
  keycloak:
    build: devops/keycloak
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb
      - KC_DB_URL_DATABASE
      - KC_DB_URL_PORT=3306
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KC_HOSTNAME
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      # Debug
      - KEYCLOAK_LOGLEVEL=true
      # - KC_PROXY=edge
    expose:
      - 8443
      - 8080
    ports:
      - 8080:8080
      - 8443:8843
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  blockchain-service:
    build: backend/blockchain-service
    ports:
      - 3000:3000
    environment:
      - ccp=PROD
    network_mode: host
    volumes:
      - "signatories:/usr/src/app/cases"
      
  sign-service:
    build: backend/sign
    network_mode: host
    volumes:
      - "signatories:/usr/src/app/cases"

volumes:
  kafka_data:
    driver: local
  signatories:
    driver: local